%extracts pulse parameters from pulse mat file associated w/ tifs
%containing traces w/ multiple pulses
function [PTfreq,PTdBampl,PTonsetInPulse,msPTpulseLen,msStimLen,msRamp,kHzSampleRate] = extractMapPulseParams(pulse)
pulseCellStr = {pulse.pulsename}';
PTonsetInPulse = str2double(strrep(strrep(string(regexp(pulseCellStr,...
    '_at_(\d{1}.\d{1}s|\d{1}s)_','match')),'_at_',''),'s_',''));
PTfreq = str2double(strrep(string(regexp(pulseCellStr,...
    '(\d{4}|\d{5})Hz_','match')),'Hz_',''));
PTdBampl = str2double(strrep(strrep(string(regexp(pulseCellStr,...
    '_\d{2}dB_','match')),'dB',''),'_',''));
msPTpulseLen = str2double(strrep(strrep(string(regexp(pulseCellStr,...
    '_\d*msPulse_','match')),'msPulse',''),'_',''));
msStimLen = str2double(strrep(strrep(string(regexp(pulseCellStr,...
    '_\d*msTotal_','match')),'msTotal',''),'_',''));
msRamp = str2double(strrep(strrep(string(regexp(pulseCellStr,...
    '_\d*msRamp_','match')),'msRamp',''),'_',''));
kHzSampleRate = str2double(strrep(strrep(string(regexp(pulseCellStr,...
    '_Fs\d*kHz','match')),'_Fs',''),'kHz',''));

