function spec = stimGroupSpec(family)
% stimGroupSpec  Registry describing one stim family's table layout.
%
%   spec = stimGroupSpec(family)
%   families = stimGroupSpec()            % cellstr of supported families
%
%   Single source of truth for everything family-specific in the cohort
%   aggregation and plotting path, so aggregateStimGroup, validateStimGroup
%   and the family plotters stay generic. Subsumes the family -> filename
%   lookup previously duplicated inside compileAnmlROItables.
%
%   Inputs:
%     family - 'BPN' or 'CGC'. Called with no arguments, returns the list of
%              supported families instead of a spec.
%
%   Output (struct):
%     .family           the family name
%     .suffixRaw        per-animal file written by stimParam2ROI
%     .suffixProcessed  per-animal file written by the process* script;
%                       this is what aggregation reads
%     .processScript    the per-animal script that turns suffixRaw into
%                       suffixProcessed (adds dF/F and peak responses)
%     .varname          table variable name inside those .mat files
%     .groupPattern     sprintf pattern for the group file name
%     .idVars           columns identifying a unique cell
%     .levelVar         the stimulus level / condition axis for plotting
%     .stimVars         columns that make a stim unique WITHIN a cell
%     .timeVar          the dF/F time axis column
%     .traceVars        columns that must match timeVar in width
%     .cellAvgVar       the per-cell (trial-averaged) trace column
%     .cellTrialVar     the PER-TRIAL trace column (nReps x nFrames per row)
%                       that cellAvgVar is the mean of
%     .rawTraceVars     raw fluorescence columns; on their own (t_total)
%                       axis, deliberately NOT width-checked against timeVar
%     .derivedVars      columns the process* script computes. Stripped before
%                       re-processing a legacy combined file, so stale or
%                       foreign derived columns cannot survive into a fresh
%                       run (dFF_PT_preDRCf0 and t_dFF_PT are listed for CGC
%                       for exactly that reason)
%     .peakVar          per-cell peak response
%     .sigVar           per-cell significance flag
%     .peakVars         all peak/significance columns
%     .requiredVars     minimum column set for a well-formed table
%     .convention       analysis parameters stamped into groupInfo; a group
%                       whose stamp disagrees with these is stale
%
%   Note on rawTraceVars: raw F columns sit on the absolute-recording-time
%   axis (t_total), not the dF/F axis, and their widths legitimately differ
%   across animals. validateStimGroup reports ragged raw traces at 'info'
%   severity only.
%
%   See also validateStimGroup, aggregateStimGroup, compileAnmlROItables.

reg = struct();

%% ---- BPN (band-pass noise) ----
reg.BPN = struct( ...
    'family',          'BPN', ...
    'suffixRaw',       '_anmlROI_BPNstimTable_raw.mat', ...
    'suffixProcessed', '_anmlROI_BPNstimTable.mat', ...
    'processScript',   'processBPN2P', ...
    'varname',         'anmlROIbyStim', ...
    'groupPattern',    'BPN_Group%s.mat', ...
    'idVars',          {{'animal','roiID'}}, ...
    'levelVar',        'BPNdBAmpl', ...
    'stimVars',        {{'BPNdBAmpl'}}, ...
    'timeVar',         't_dFF', ...
    'traceVars',       {{'dFF','dFF_avg'}}, ...
    'cellAvgVar',      'dFF_avg', ...
    'cellTrialVar',    'dFF', ...
    'rawTraceVars',    {{'rawFroi','moCorRawFroi','fissaFroi','SCALEDfissaFroi'}}, ...
    'derivedVars',     {{'t_total','t_dFF','dFF','dFF_avg','sigPeak','sig','pkResp'}}, ...
    'peakVar',         'pkResp', ...
    'sigVar',          'sig', ...
    'peakVars',        {{'sigPeak','sig','pkResp'}}, ...
    'requiredVars',    {{'animal','roiID','frameRate','treatment', ...
                         'BPNsOnset','BPNdBAmpl','BPNmsPulseLen', ...
                         't_dFF','dFF','dFF_avg','sig','pkResp'}}, ...
    'convention',      struct('baselineSec',1,'pkBPNsigSD',2,'nFramesPostPulse',2));

%% ---- CGC (pure tone in contrast DRC) ----
reg.CGC = struct( ...
    'family',          'CGC', ...
    'suffixRaw',       '_anmlROI_CGCstimTable_raw.mat', ...
    'suffixProcessed', '_anmlROI_CGCstimTable.mat', ...
    'processScript',   'processCGC', ...
    'varname',         'anmlROIbyStim', ...
    'groupPattern',    'CGC_Group%s.mat', ...
    'idVars',          {{'animal','roiID'}}, ...
    'levelVar',        'dBdelta', ...
    'stimVars',        {{'dBdelta'}}, ...
    'timeVar',         't_dFF_DRC', ...
    'traceVars',       {{'dFF_DRC','dFF_DRC_avg','dFF_PT','dFF_PT_avg'}}, ...
    'cellAvgVar',      'dFF_PT_avg', ...
    'cellTrialVar',    'dFF_PT', ...
    'rawTraceVars',    {{'rawFroi','moCorRawFroi','fissaFroi','SCALEDfissaFroi'}}, ...
    'derivedVars',     {{'t_total','t_dFF_DRC','dFF_DRC','dFF_DRC_avg', ...
                         'dFF_PT','dFF_PT_avg','pkPT_sig','sigPk','pkPT', ...
                         't_dFF_PT','dFF_PT_preDRCf0'}}, ...
    'peakVar',         'pkPT', ...
    'sigVar',          'sigPk', ...
    'peakVars',        {{'pkPT_sig','sigPk','pkPT'}}, ...
    'requiredVars',    {{'animal','roiID','frameRate','treatment','trigDelay', ...
                         'PTsOnset','dBdelta', ...
                         't_dFF_DRC','dFF_DRC','dFF_PT','dFF_PT_avg','sigPk','pkPT'}}, ...
    'convention',      struct('tBasePT',[1 2],'pkPTframeBin',4,'pkPTsigSD',2, ...
                              'tBaseDRC',[-1.2 0]));

%% ---- FRA (frequency response area / pure-tone mapping) ----
% FRA differs from BPN/CGC in two ways worth knowing before editing this:
%
%   1. There is no _raw stage. The per-animal artifact is built directly by
%      processFRA -> FRAmap from tifFileList, so suffixRaw is empty and
%      processScript writes suffixProcessed itself (via FRAmap2table).
%   2. A stim is identified by TWO variables, freqHz and dBSPL, not one.
%      levelVar is the sound level because that is the axis thresholds and
%      rate-level structure live on; frequency is the other stim axis.
%
% There is no per-trial trace column: FRAmap keeps only the trial average it
% tested (plus per-trial PEAKS in the struct, as pkDFFbyTrial). cellTrialVar
% is therefore empty, and any plotter must not assume it exists.
reg.FRA = struct( ...
    'family',          'FRA', ...
    'suffixRaw',       '', ...
    'suffixProcessed', '_anmlROI_FRAtable.mat', ...
    'processScript',   'processFRA', ...
    'varname',         'anmlROIbyFRA', ...
    'groupPattern',    'FRA_Group%s.mat', ...
    'idVars',          {{'animal','roiID'}}, ...
    'levelVar',        'dBSPL', ...
    'stimVars',        {{'freqHz','dBSPL'}}, ...
    'timeVar',         't_PTrel', ...
    'traceVars',       {{'dFFavg'}}, ...
    'cellAvgVar',      'dFFavg', ...
    'cellTrialVar',    '', ...
    'rawTraceVars',    {{}}, ...
    'derivedVars',     {{'t_PTrel','dFFavg','pkDFF','sig','nTrials'}}, ...
    'peakVar',         'pkDFF', ...
    'sigVar',          'sig', ...
    'peakVars',        {{'pkDFF','sig'}}, ...
    'requiredVars',    {{'animal','roiID','frameRate','treatment', ...
                         'freqHz','dBSPL','t_PTrel','dFFavg','sig','pkDFF'}}, ...
    'convention',      struct('pkPTsigSD',2,'nFramesPostPulse',2, ...
                              'sigMethod','trialAveraged', ...
                              'baseline','preOnsetExclusive'));

%% ---- dispatch ----
if nargin == 0
    spec = fieldnames(reg)';
    return
end

family = char(family);
if ~isfield(reg, family)
    error('stimGroupSpec:UnknownFamily', ...
        'Unknown family "%s". Supported: %s', family, strjoin(fieldnames(reg)', ', '));
end
spec = reg.(family);
end
